version: '3.8'

services:
  nodejs-api:
    image: gestion_patient:latest
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: medirendez
    networks:
      - crud_backend_gestion_patient_default

  mysql:
    image: mysqldb:latest
    ports:
      - "3336:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: medirendez
    volumes:
      - C:\Users\informasud\Downloads\medirendez (5).sql:/docker-entrypoint-initdb.d/medirendez.sql
    networks:
      - crud_backend_gestion_patient_default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: root
    networks:
      - crud_backend_gestion_patient_default

networks:
  crud_backend_gestion_patient_default:
    external: true
