version: '3.8'

services:
  nodejs-api:
    image: gestion_patient:latest
    ports:
      - "3000:3000"
    networks:
      - crud_backend_gestion_patient_default

  mysql:
    image: mysql:latest
    ports:
      - "3336:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: medirendez
    volumes:
      - E:\test\Crud_Backend_gestion_patient\docker\init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crud_backend_gestion_patient_default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 
    networks:
      - crud_backend_gestion_patient_default

networks:
  crud_backend_gestion_patient_default:
    external: true
